[package]
name = "col"
version = "0.1.0"
description = "Interpreter for the col language"
authors = ["Cassaundra <cass@cassaundra.io>"]
edition = "2018"

[dependencies]
clap = "2.32.0"

#[[bin]]
#name = "coli"